[2024-09-17T13:12:28.873+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T13:12:28.913+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.create_pet_table manual__2024-09-17T13:09:27.941176+00:00 [queued]>
[2024-09-17T13:12:28.932+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.create_pet_table manual__2024-09-17T13:09:27.941176+00:00 [queued]>
[2024-09-17T13:12:28.932+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2024-09-17T13:12:28.960+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): create_pet_table> on 2024-09-17 13:09:27.941176+00:00
[2024-09-17T13:12:28.980+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rasa_data_ingestion_dag', 'create_pet_table', 'manual__2024-09-17T13:09:27.941176+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/rasa_data_ingestion_dag.py', '--cfg-path', '/tmp/tmpfa_kh5za']
[2024-09-17T13:12:28.985+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask create_pet_table
[2024-09-17T13:12:28.990+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-17T13:12:28.991+0000] {standard_task_runner.py:72} INFO - Started process 1215 to run task
[2024-09-17T13:12:29.078+0000] {task_command.py:467} INFO - Running <TaskInstance: rasa_data_ingestion_dag.create_pet_table manual__2024-09-17T13:09:27.941176+00:00 [running]> on host aca847883b6e
[2024-09-17T13:12:29.257+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Eric Silveira' AIRFLOW_CTX_DAG_ID='rasa_data_ingestion_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T13:09:27.941176+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T13:09:27.941176+00:00'
[2024-09-17T13:12:29.259+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T13:12:29.263+0000] {sql.py:266} INFO - Executing: 
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'events';
          
[2024-09-17T13:12:29.283+0000] {base.py:84} INFO - Retrieving connection 'conn_db_***'
[2024-09-17T13:12:29.302+0000] {base.py:84} INFO - Retrieving connection 'conn_db_***'
[2024-09-17T13:12:29.311+0000] {sql.py:509} INFO - Running statement: 
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'events';
          , parameters: None
[2024-09-17T13:12:29.324+0000] {sql.py:518} INFO - Rows affected: 7
[2024-09-17T13:12:29.368+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T13:12:29.369+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_data_ingestion_dag, task_id=create_pet_table, run_id=manual__2024-09-17T13:09:27.941176+00:00, execution_date=20240917T130927, start_date=20240917T131228, end_date=20240917T131229
[2024-09-17T13:12:29.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T13:12:29.467+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-17T13:12:29.469+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
