[2024-09-15T21:56:45.763+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:45.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:56:45.764+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:56:45.764+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:45.765+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:56:45.765+0000] {dagbag.py:365} INFO - File /opt/airflow/dags/dag_rasa.py assumed to contain no DAGs. Skipping.
[2024-09-15T21:56:45.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:45.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T21:56:52.820+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:52.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:56:52.823+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:56:52.823+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:52.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:52.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T21:56:56.876+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:56.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:56:56.878+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:56:56.878+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:56.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:56:56.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.023 seconds
[2024-09-15T21:57:00.923+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:00.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:57:00.926+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:00.925+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:00.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:00.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.022 seconds
[2024-09-15T21:57:16.048+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:16.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:57:16.051+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:16.050+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:16.055+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:16.053+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 1, in <module>
    from airflow import dag
ImportError: cannot import name 'dag' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T21:57:16.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:16.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.036 seconds
[2024-09-15T21:57:20.090+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:20.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:57:20.093+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:20.093+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:20.095+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:20.094+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3
    @dag
SyntaxError: invalid syntax
[2024-09-15T21:57:20.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:20.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T21:57:22.141+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:22.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:57:22.144+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:22.144+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:22.146+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:22.146+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:57:22.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:22.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.030 seconds
[2024-09-15T21:57:25.186+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:25.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:57:25.189+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:25.188+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:25.191+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:25.190+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:57:25.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:25.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.030 seconds
[2024-09-15T21:57:29.247+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:29.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:57:29.250+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:29.250+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:29.253+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:29.252+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:57:29.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:29.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T21:57:30.267+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:30.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:57:30.270+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:30.269+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:30.273+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:30.272+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:57:30.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:30.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T21:57:34.333+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:34.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:57:34.336+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:34.335+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:34.338+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:57:34.337+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:57:34.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:57:34.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.047 seconds
[2024-09-15T21:58:04.565+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:58:04.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:58:04.571+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:58:04.570+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:58:04.573+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:58:04.572+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:58:04.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:58:04.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T21:58:34.776+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:58:34.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:58:34.782+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:58:34.781+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:58:34.784+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:58:34.783+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:58:34.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:58:34.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T21:59:04.985+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:04.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:59:04.991+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:59:04.991+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:04.994+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:59:04.993+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:59:04.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:05.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.035 seconds
[2024-09-15T21:59:35.201+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:35.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:59:35.206+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:59:35.206+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:35.209+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:59:35.208+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:59:35.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:35.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T21:59:46.284+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:46.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T21:59:46.290+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:59:46.289+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:46.292+0000] {logging_mixin.py:190} INFO - [2024-09-15T21:59:46.291+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T21:59:46.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T21:59:46.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:00:03.435+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:03.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:03.438+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:03.437+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:03.441+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:03.439+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:03.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:03.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:00:09.491+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:09.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:09.496+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:09.496+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:09.500+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:09.499+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:09.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:09.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.044 seconds
[2024-09-15T22:00:12.544+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:12.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:12.546+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:12.546+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:12.551+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:12.549+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:12.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:12.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.039 seconds
[2024-09-15T22:00:16.600+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:16.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:16.604+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:16.603+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:16.607+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:16.606+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:16.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:16.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.034 seconds
[2024-09-15T22:00:17.671+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:17.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:17.675+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:17.674+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:17.679+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:17.677+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:17.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:17.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.043 seconds
[2024-09-15T22:00:19.687+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:19.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:19.691+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:19.691+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:19.696+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:19.694+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 4
    dag_id=
    ^^^^^^^
SyntaxError: expected argument value expression
[2024-09-15T22:00:19.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:19.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.043 seconds
[2024-09-15T22:00:21.765+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:21.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:21.768+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:21.767+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:21.770+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:21.769+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:21.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:21.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T22:00:24.794+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:24.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:24.797+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:24.796+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:24.801+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:24.800+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:24.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:24.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.037 seconds
[2024-09-15T22:00:27.853+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:27.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:27.856+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:27.856+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:27.863+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:27.861+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:27.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:27.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.064 seconds
[2024-09-15T22:00:32.906+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:32.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:32.909+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:32.909+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:32.912+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:32.911+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:32.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:32.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.034 seconds
[2024-09-15T22:00:35.933+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:35.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:00:35.939+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:35.939+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:35.942+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:00:35.941+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 6
    )
SyntaxError: invalid syntax
[2024-09-15T22:00:35.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:00:35.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.036 seconds
[2024-09-15T22:01:06.175+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:01:06.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:01:06.178+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:01:06.178+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:01:06.184+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:01:06.182+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 6
    )
SyntaxError: invalid syntax
[2024-09-15T22:01:06.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:01:06.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.047 seconds
[2024-09-15T22:01:36.384+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:01:36.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:01:36.388+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:01:36.388+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:01:36.394+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:01:36.391+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 6
    )
SyntaxError: invalid syntax
[2024-09-15T22:01:36.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:01:36.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.049 seconds
[2024-09-15T22:02:06.653+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:02:06.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:02:06.659+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:02:06.659+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:02:06.662+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:02:06.661+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 6
    )
SyntaxError: invalid syntax
[2024-09-15T22:02:06.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:02:06.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T22:02:36.881+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:02:36.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:02:36.884+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:02:36.883+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:02:36.886+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:02:36.885+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 6
    )
SyntaxError: invalid syntax
[2024-09-15T22:02:36.887+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:02:36.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T22:03:07.111+0000] {processor.py:186} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:07.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:03:07.115+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:07.115+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:07.118+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:07.117+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 6
    )
SyntaxError: invalid syntax
[2024-09-15T22:03:07.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:07.142+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.036 seconds
[2024-09-15T22:03:29.259+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:29.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:03:29.262+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:29.261+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:29.266+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:29.264+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 4
    dag_id='dag_ingestion_rasa'
           
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:03:29.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:29.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.038 seconds
[2024-09-15T22:03:34.331+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:34.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:03:34.334+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:34.333+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:34.338+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:34.337+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 4
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:03:34.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:34.368+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.045 seconds
[2024-09-15T22:03:40.380+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:40.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:03:40.383+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:40.383+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:40.390+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:40.388+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 2
    from date
             ^
SyntaxError: invalid syntax
[2024-09-15T22:03:40.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:40.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.066 seconds
[2024-09-15T22:03:42.439+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:42.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:03:42.444+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:42.443+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:42.451+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:42.447+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 2
    from datetime
                 ^
SyntaxError: invalid syntax
[2024-09-15T22:03:42.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:42.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.062 seconds
[2024-09-15T22:03:46.512+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:46.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:03:46.519+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:46.518+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:46.528+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:46.524+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:03:46.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:46.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.101 seconds
[2024-09-15T22:03:56.778+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:56.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:03:56.785+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:56.784+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:56.799+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:03:56.796+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:03:56.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:03:56.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.115 seconds
[2024-09-15T22:04:27.316+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:27.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:27.322+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:27.321+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:27.326+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:27.324+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:04:27.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:27.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.041 seconds
[2024-09-15T22:04:35.427+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:35.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:35.430+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:35.430+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:35.433+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:35.432+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:04:35.433+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:35.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T22:04:37.447+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:37.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:37.450+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:37.450+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:37.453+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:37.452+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:04:37.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:37.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:04:40.519+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:40.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:40.522+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:40.521+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:40.524+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:40.523+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:04:40.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:40.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:04:42.544+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:42.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:42.549+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:42.548+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:42.553+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:42.552+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:04:42.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:42.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.041 seconds
[2024-09-15T22:04:46.610+0000] {processor.py:186} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:46.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:46.613+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:46.612+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:46.616+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:46.615+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:04:46.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:46.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:04:47.637+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:47.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:47.639+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:47.639+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:47.642+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:47.641+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:04:47.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:47.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T22:04:48.675+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:48.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:48.678+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:48.678+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:48.681+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:48.680+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 5
    dag_id='dag_ingestion_rasa'
           ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-09-15T22:04:48.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:48.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:04:52.728+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:52.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:52.731+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:52.730+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:52.733+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:52.732+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 7
    )
SyntaxError: invalid syntax
[2024-09-15T22:04:52.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:52.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.030 seconds
[2024-09-15T22:04:59.794+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:59.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:04:59.796+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:59.796+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:59.799+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:04:59.798+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 7
    schedule=
    ^^^^^^^^^
SyntaxError: expected argument value expression
[2024-09-15T22:04:59.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:04:59.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T22:05:01.832+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:01.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:01.835+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:01.835+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:01.838+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:01.837+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 8
    )
SyntaxError: invalid syntax
[2024-09-15T22:05:01.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:01.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.038 seconds
[2024-09-15T22:05:04.880+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:04.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:04.885+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:04.884+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:04.890+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:04.888+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 8
    )
SyntaxError: invalid syntax
[2024-09-15T22:05:04.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:04.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:05:06.919+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:06.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:06.922+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:06.922+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:06.925+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:06.924+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 8
    )
SyntaxError: invalid syntax
[2024-09-15T22:05:06.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:06.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.030 seconds
[2024-09-15T22:05:19.025+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:19.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:19.028+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:19.028+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:19.031+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:19.030+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 8
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-09-15T22:05:19.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:19.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T22:05:22.059+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:22.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:22.063+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:22.062+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:22.065+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:22.064+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 8
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-09-15T22:05:22.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:22.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T22:05:35.186+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:35.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:35.189+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:35.189+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:35.192+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:35.191+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 16
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-09-15T22:05:35.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:35.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T22:05:40.227+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:40.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:40.230+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:40.229+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:40.233+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:40.231+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 16
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-09-15T22:05:40.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:40.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T22:05:48.324+0000] {processor.py:186} INFO - Started process (PID=286) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:48.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:48.328+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:48.327+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:48.330+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:48.329+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 17
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-09-15T22:05:48.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:48.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:05:50.361+0000] {processor.py:186} INFO - Started process (PID=287) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:50.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:50.364+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:50.364+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:50.367+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:50.366+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 17
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-09-15T22:05:50.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:50.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:05:52.402+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:52.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:52.405+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:52.404+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:52.407+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:52.406+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 17
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-09-15T22:05:52.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:52.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:05:56.454+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:56.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:05:56.460+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:56.460+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:56.463+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:05:56.462+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 17
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-09-15T22:05:56.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:05:56.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:06:00.513+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:00.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:06:00.518+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:06:00.518+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:00.522+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:06:00.521+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 17
    )
SyntaxError: invalid syntax
[2024-09-15T22:06:00.523+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:00.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.042 seconds
[2024-09-15T22:06:11.617+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:11.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:06:11.623+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:06:11.622+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:11.627+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:06:11.625+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 18
    )
SyntaxError: invalid syntax
[2024-09-15T22:06:11.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:11.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.036 seconds
[2024-09-15T22:06:41.839+0000] {processor.py:186} INFO - Started process (PID=298) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:41.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:06:41.845+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:06:41.845+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:41.848+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:06:41.847+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 18
    )
SyntaxError: invalid syntax
[2024-09-15T22:06:41.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:06:41.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:07:12.098+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:12.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:07:12.103+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:12.103+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:12.106+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:12.105+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 18
    )
SyntaxError: invalid syntax
[2024-09-15T22:07:12.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:12.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.034 seconds
[2024-09-15T22:07:42.321+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:42.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:07:42.327+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:42.326+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:42.330+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:42.329+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 18
    )
SyntaxError: invalid syntax
[2024-09-15T22:07:42.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:42.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.035 seconds
[2024-09-15T22:07:43.337+0000] {processor.py:186} INFO - Started process (PID=312) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:43.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:07:43.340+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:43.340+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:43.343+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:43.342+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 19
    de
    ^^
SyntaxError: invalid syntax
[2024-09-15T22:07:43.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:43.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.035 seconds
[2024-09-15T22:07:44.387+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:44.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:07:44.390+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:44.390+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:44.392+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:44.392+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 19
    def 
        ^
SyntaxError: invalid syntax
[2024-09-15T22:07:44.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:44.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.028 seconds
[2024-09-15T22:07:52.462+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:52.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:07:52.465+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:52.464+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:52.467+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:52.466+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 19
    def dag_ingestion_rasa
                          ^
SyntaxError: expected '('
[2024-09-15T22:07:52.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:52.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.028 seconds
[2024-09-15T22:07:55.508+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:55.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:07:55.511+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:55.511+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:55.515+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:55.513+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 19
    def dag_ingestion_rasa()
                            ^
SyntaxError: expected ':'
[2024-09-15T22:07:55.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:55.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.034 seconds
[2024-09-15T22:07:56.544+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:56.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:07:56.546+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:56.546+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:56.549+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:56.548+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 19
    def dag_ingestion_rasa():
                             ^
IndentationError: expected an indented block after function definition on line 19
[2024-09-15T22:07:56.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:56.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:07:59.596+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:59.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:07:59.602+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:59.602+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:59.605+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:07:59.604+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 20
    
    ^
IndentationError: expected an indented block after function definition on line 19
[2024-09-15T22:07:59.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:07:59.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T22:08:03.643+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:03.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:03.645+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:03.645+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:03.648+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:03.647+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 20
    @task
         ^
IndentationError: unexpected unindent
[2024-09-15T22:08:03.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:03.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.036 seconds
[2024-09-15T22:08:05.685+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:05.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:05.689+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:05.688+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:05.692+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:05.691+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 20
    
    ^
IndentationError: expected an indented block after function definition on line 19
[2024-09-15T22:08:05.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:05.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.038 seconds
[2024-09-15T22:08:09.739+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:09.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:09.742+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:09.742+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:09.745+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:09.744+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3
    from 
         ^
SyntaxError: invalid syntax
[2024-09-15T22:08:09.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:09.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T22:08:13.799+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:13.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:13.805+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:13.805+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:13.808+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:13.807+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3
    from airflow.
                 ^
SyntaxError: invalid syntax
[2024-09-15T22:08:13.808+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:13.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.034 seconds
[2024-09-15T22:08:15.832+0000] {processor.py:186} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:15.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:15.835+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:15.834+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:15.837+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:15.836+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3
    from airflow.operators
                          ^
SyntaxError: invalid syntax
[2024-09-15T22:08:15.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:15.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T22:08:19.901+0000] {processor.py:186} INFO - Started process (PID=335) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:19.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:19.903+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:19.903+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:19.907+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:19.906+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 21
    
    ^
IndentationError: expected an indented block after function definition on line 20
[2024-09-15T22:08:19.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:19.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T22:08:24.964+0000] {processor.py:186} INFO - Started process (PID=336) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:24.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:24.967+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:24.967+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:24.970+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:24.969+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 21
    
    ^
IndentationError: expected an indented block after function definition on line 20
[2024-09-15T22:08:24.970+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:24.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:08:28.009+0000] {processor.py:186} INFO - Started process (PID=337) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:28.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:28.015+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:28.015+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:28.018+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:28.017+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 22
    
    ^
IndentationError: expected an indented block after function definition on line 20
[2024-09-15T22:08:28.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:28.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.032 seconds
[2024-09-15T22:08:34.160+0000] {processor.py:186} INFO - Started process (PID=338) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:34.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:34.163+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:34.162+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:34.168+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:34.165+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:08:34.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:34.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.036 seconds
[2024-09-15T22:08:36.189+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:36.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:36.192+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:36.192+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:36.197+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:36.195+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:08:36.199+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:36.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.035 seconds
[2024-09-15T22:08:47.319+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:47.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:47.325+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:47.324+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:47.330+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:47.327+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:08:47.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:47.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.036 seconds
[2024-09-15T22:08:49.341+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:49.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:49.345+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:49.344+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:49.349+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:49.347+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:08:49.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:49.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:08:53.419+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:53.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:53.425+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:53.424+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:53.430+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:53.427+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:08:53.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:53.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.039 seconds
[2024-09-15T22:08:55.448+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:55.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:55.451+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:55.450+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:55.455+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:55.453+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:08:55.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:55.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.036 seconds
[2024-09-15T22:08:59.530+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:59.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:08:59.536+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:59.536+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:59.541+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:08:59.538+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:08:59.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:08:59.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.037 seconds
[2024-09-15T22:09:00.550+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:00.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:09:00.553+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:00.553+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:00.559+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:00.556+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:09:00.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:00.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.037 seconds
[2024-09-15T22:09:04.622+0000] {processor.py:186} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:04.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:09:04.624+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:04.624+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:04.630+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:04.627+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators import EmptyOperator
ImportError: cannot import name 'EmptyOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/__init__.py)
[2024-09-15T22:09:04.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:04.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.042 seconds
[2024-09-15T22:09:29.814+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:29.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:09:29.820+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:29.819+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:29.828+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:29.825+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 3, in <module>
    from airflow.operators.E import EmptyOperator
ModuleNotFoundError: No module named 'airflow.operators.E'
[2024-09-15T22:09:29.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:29.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.060 seconds
[2024-09-15T22:09:30.839+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:30.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:09:30.842+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:30.842+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:30.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:30.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.027 seconds
[2024-09-15T22:09:33.873+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:33.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:09:33.876+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:33.875+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:33.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:33.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.023 seconds
[2024-09-15T22:09:50.022+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:50.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:09:50.028+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:50.028+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:50.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:50.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.026 seconds
[2024-09-15T22:09:53.055+0000] {processor.py:186} INFO - Started process (PID=369) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:53.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:09:53.061+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:53.060+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:53.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:53.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.028 seconds
[2024-09-15T22:09:58.125+0000] {processor.py:186} INFO - Started process (PID=370) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:58.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:09:58.129+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:09:58.129+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:58.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:09:58.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.031 seconds
[2024-09-15T22:10:17.267+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:17.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:10:17.273+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:10:17.272+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:17.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:17.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:10:31.400+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:31.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:10:31.403+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:10:31.403+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:31.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:31.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.062 seconds
[2024-09-15T22:10:33.419+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:33.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:10:33.422+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:10:33.422+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:33.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:33.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.025 seconds
[2024-09-15T22:10:36.447+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:36.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:10:36.450+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:10:36.450+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:36.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:36.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.024 seconds
[2024-09-15T22:10:37.498+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:37.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:10:37.501+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:10:37.501+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:37.504+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:37.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.023 seconds
[2024-09-15T22:10:38.516+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:38.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:10:38.520+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:10:38.519+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:38.521+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:10:38.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.025 seconds
[2024-09-15T22:11:02.719+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:02.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:02.725+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:02.725+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:02.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:02.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.027 seconds
[2024-09-15T22:11:05.781+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:05.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:05.784+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:05.784+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:05.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:05.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.025 seconds
[2024-09-15T22:11:08.817+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:08.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:08.823+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:08.822+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:08.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:08.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:11:10.872+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:10.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:10.875+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:10.874+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:10.880+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:10.877+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 23
    end = EmptyOperator(task_id=)
                        ^^^^^^^^
SyntaxError: expected argument value expression
[2024-09-15T22:11:10.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:10.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.038 seconds
[2024-09-15T22:11:12.905+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:12.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:12.909+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:12.908+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:12.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:12.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:11:23.017+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:23.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:23.020+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:23.020+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:23.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:23.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.028 seconds
[2024-09-15T22:11:24.033+0000] {processor.py:186} INFO - Started process (PID=401) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:24.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:24.036+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:24.035+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:24.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:24.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.026 seconds
[2024-09-15T22:11:31.127+0000] {processor.py:186} INFO - Started process (PID=402) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:31.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:31.131+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:31.131+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:31.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:31.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.028 seconds
[2024-09-15T22:11:33.149+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:33.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:33.155+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:33.155+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:33.159+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:33.157+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 27, in <module>
    da
NameError: name 'da' is not defined
[2024-09-15T22:11:33.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:33.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.037 seconds
[2024-09-15T22:11:38.225+0000] {processor.py:186} INFO - Started process (PID=404) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:38.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:38.228+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:38.228+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:38.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:38.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.029 seconds
[2024-09-15T22:11:40.254+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:40.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:11:40.258+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.257+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:40.281+0000] {processor.py:925} INFO - DAG(s) 'dag_ingestion_rasa' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:11:40.556+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.555+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:dag_ingestion_rasa
[2024-09-15T22:11:40.565+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.565+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:dag_ingestion_rasa
[2024-09-15T22:11:40.572+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.572+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:dag_ingestion_rasa
[2024-09-15T22:11:40.579+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.579+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:dag_ingestion_rasa
[2024-09-15T22:11:40.586+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.586+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:dag_ingestion_rasa
[2024-09-15T22:11:40.594+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.593+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:dag_ingestion_rasa
[2024-09-15T22:11:40.599+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.599+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:dag_ingestion_rasa
[2024-09-15T22:11:40.600+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.599+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:11:40.614+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.614+0000] {dag.py:3252} INFO - Creating ORM DAG for dag_ingestion_rasa
[2024-09-15T22:11:40.626+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:11:40.626+0000] {dag.py:4156} INFO - Setting next_dagrun for dag_ingestion_rasa to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:11:40.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.400 seconds
[2024-09-15T22:12:02.442+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:02.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:02.445+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:02.444+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:02.450+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:02.447+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 27, in <module>
    instanciadag_ingestion_rasa()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'instanciadag_ingestion_rasa' is not defined
[2024-09-15T22:12:02.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:02.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.037 seconds
[2024-09-15T22:12:03.452+0000] {processor.py:186} INFO - Started process (PID=413) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:03.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:03.455+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:03.454+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:03.459+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:03.457+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 27, in <module>
    instancia_dag_ingestion_rasa()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'instancia_dag_ingestion_rasa' is not defined
[2024-09-15T22:12:03.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:03.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:12:05.473+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:05.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:05.476+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:05.476+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:05.481+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:05.479+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 27, in <module>
    instancia_dadag_ingestion_rasa()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'instancia_dadag_ingestion_rasa' is not defined
[2024-09-15T22:12:05.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:05.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.033 seconds
[2024-09-15T22:12:08.537+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:08.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:08.542+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:08.541+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:08.547+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:08.545+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag_rasa.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_rasa.py", line 27, in <module>
    instancia_dag_ingestiondag_ingestion_rasa()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'instancia_dag_ingestiondag_ingestion_rasa' is not defined
[2024-09-15T22:12:08.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:08.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.034 seconds
[2024-09-15T22:12:09.556+0000] {processor.py:186} INFO - Started process (PID=416) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:09.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:09.559+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:09.558+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:09.568+0000] {processor.py:925} INFO - DAG(s) 'dag_ingestion_rasa' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:09.583+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:09.583+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:12:09.607+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:09.607+0000] {dag.py:4156} INFO - Setting next_dagrun for dag_ingestion_rasa to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:12:09.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.077 seconds
[2024-09-15T22:12:39.804+0000] {processor.py:186} INFO - Started process (PID=422) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:39.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:39.808+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:39.807+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:39.819+0000] {processor.py:925} INFO - DAG(s) 'dag_ingestion_rasa' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:39.849+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:39.849+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:12:39.873+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:39.873+0000] {dag.py:4156} INFO - Setting next_dagrun for dag_ingestion_rasa to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:12:39.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.095 seconds
[2024-09-15T22:12:44.863+0000] {processor.py:186} INFO - Started process (PID=423) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:44.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:44.866+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:44.865+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:44.876+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:45.017+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.017+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:rasa_data_ingestion_dag
[2024-09-15T22:12:45.026+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.026+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:rasa_data_ingestion_dag
[2024-09-15T22:12:45.032+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.032+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:rasa_data_ingestion_dag
[2024-09-15T22:12:45.039+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.039+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:rasa_data_ingestion_dag
[2024-09-15T22:12:45.045+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.045+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:rasa_data_ingestion_dag
[2024-09-15T22:12:45.051+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.051+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:rasa_data_ingestion_dag
[2024-09-15T22:12:45.058+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.057+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:rasa_data_ingestion_dag
[2024-09-15T22:12:45.058+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.058+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:12:45.070+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.070+0000] {dag.py:3252} INFO - Creating ORM DAG for rasa_data_ingestion_dag
[2024-09-15T22:12:45.079+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.079+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:12:45.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.235 seconds
[2024-09-15T22:12:45.953+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:45.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:45.956+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.956+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:45.965+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:45.978+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:45.978+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:12:46.007+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:46.006+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:12:46.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.080 seconds
[2024-09-15T22:12:55.028+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:55.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:12:55.031+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:55.030+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:55.043+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:12:55.059+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:55.059+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:12:55.082+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:12:55.082+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:12:55.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.081 seconds
[2024-09-15T22:13:25.326+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:13:25.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:13:25.330+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:13:25.330+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:13:25.342+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:13:25.374+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:13:25.373+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:13:25.398+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:13:25.398+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:13:25.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.124 seconds
[2024-09-15T22:13:55.553+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:13:55.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:13:55.559+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:13:55.559+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:13:55.568+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:13:55.594+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:13:55.594+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:13:55.617+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:13:55.617+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:13:55.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.126 seconds
[2024-09-15T22:14:25.848+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:14:25.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:14:25.854+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:14:25.854+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:14:25.863+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:14:25.885+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:14:25.885+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:14:25.906+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:14:25.906+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:14:25.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.080 seconds
[2024-09-15T22:14:56.125+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:14:56.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:14:56.130+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:14:56.130+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:14:56.138+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:14:56.162+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:14:56.162+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:14:56.187+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:14:56.187+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:14:56.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.086 seconds
[2024-09-15T22:15:26.378+0000] {processor.py:186} INFO - Started process (PID=466) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:15:26.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:15:26.383+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:15:26.383+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:15:26.392+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:15:26.417+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:15:26.417+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:15:26.442+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:15:26.441+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:15:26.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.086 seconds
[2024-09-15T22:15:56.668+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:15:56.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:15:56.672+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:15:56.672+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:15:56.680+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:15:56.706+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:15:56.705+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:15:56.731+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:15:56.731+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:15:56.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.087 seconds
[2024-09-15T22:16:26.886+0000] {processor.py:186} INFO - Started process (PID=480) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:16:26.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:16:26.891+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:16:26.891+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:16:26.900+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:16:26.925+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:16:26.925+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:16:26.949+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:16:26.949+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:16:26.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.086 seconds
[2024-09-15T22:16:57.160+0000] {processor.py:186} INFO - Started process (PID=487) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:16:57.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:16:57.165+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:16:57.165+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:16:57.174+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:16:57.199+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:16:57.198+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:16:57.222+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:16:57.222+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:16:57.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.085 seconds
[2024-09-15T22:17:27.364+0000] {processor.py:186} INFO - Started process (PID=494) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:17:27.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:17:27.366+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:17:27.366+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:17:27.375+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:17:27.401+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:17:27.401+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:17:27.427+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:17:27.426+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:17:27.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.085 seconds
[2024-09-15T22:17:57.666+0000] {processor.py:186} INFO - Started process (PID=501) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:17:57.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:17:57.670+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:17:57.670+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:17:57.679+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:17:57.703+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:17:57.703+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:17:57.726+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:17:57.726+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:17:57.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.084 seconds
[2024-09-15T22:18:27.911+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:18:27.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:18:27.913+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:18:27.913+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:18:27.922+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:18:27.947+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:18:27.946+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:18:27.972+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:18:27.972+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:18:27.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.084 seconds
[2024-09-15T22:18:58.205+0000] {processor.py:186} INFO - Started process (PID=515) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:18:58.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:18:58.213+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:18:58.213+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:18:58.222+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:18:58.247+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:18:58.246+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:18:58.270+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:18:58.270+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:18:58.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.086 seconds
[2024-09-15T22:19:28.439+0000] {processor.py:186} INFO - Started process (PID=522) to work on /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:19:28.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_rasa.py for tasks to queue
[2024-09-15T22:19:28.444+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:19:28.443+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:19:28.452+0000] {processor.py:925} INFO - DAG(s) 'rasa_data_ingestion_dag' retrieved from /opt/airflow/dags/dag_rasa.py
[2024-09-15T22:19:28.479+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:19:28.478+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T22:19:28.503+0000] {logging_mixin.py:190} INFO - [2024-09-15T22:19:28.503+0000] {dag.py:4156} INFO - Setting next_dagrun for rasa_data_ingestion_dag to 2024-09-14 00:00:00+00:00, run_after=2024-09-15 00:00:00+00:00
[2024-09-15T22:19:28.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_rasa.py took 0.086 seconds
